"""empty message

Revision ID: 37ce0f7e8e88
Revises: 
Create Date: 2023-09-02 21:49:33.704993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ce0f7e8e88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('college', sa.String(length=20), nullable=True),
    sa.Column('teacher', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('email_verification',
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('verification', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('score',
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('chinese', sa.Integer(), nullable=True),
    sa.Column('math', sa.Integer(), nullable=True),
    sa.Column('english', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('student',
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('college', sa.String(length=10), nullable=True),
    sa.Column('major', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('score')
    op.drop_table('email_verification')
    op.drop_table('course')
    # ### end Alembic commands ###
